### ISSUE TITLE
Shop doesn't accept same item after reload

### ISSUE THREAD

**Issue by TetraTheta** [snowgears/shopbugs#161]
### Describe the bug
After `/shop reload`, shop doesn't accept the item which is used when making shop.

### To Reproduce
1. Get customized item via `/give @p carrot_on_a_stick{display:{Name:'{"text":"Credit Coupon #01","color":"aqua"}',Lore:['{"text":"Exchange for $100"}','{"text":"Coupon ID #01"}']},Unbreakable:1b,CustomModelData:1} 1`  
Since this plugin doesn't accept custom tags(tags are ignored when item wrote to YAML file), I didn't used tags such as CustomTags:1,CustomTagsTwo:2`.
2. Create shop with that item. I made 'buy admin' shop.
3. Run `/shop reload`
4. Try to sell item to the shop. You cannot sell your item which is used to create shop.

### Expected behavior
You can sell item which is used to make shop to shop.  
I even checked `admin.yml` because I tried with 'buy admin' shop.
```yaml
    '20':
      location: world,51,64,-465
      price: 100.0
      amount: 1
      type: admin buy
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: CARROT_ON_A_STICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '§bCredit Coupon #01'
          lore:
          - Exchange for $100
          - 'Coupon ID #01'
          custom-model-data: 1
          Unbreakable: true
```
This seems to containing every NBT tags that used in command... But I don't know why shop doesn't accept my item.

### Screenshots
![2020-10-19_22 53 15](https://user-images.githubusercontent.com/37061801/96460361-15637f00-125e-11eb-9f45-070e972a45f7.png)  
Using command that described above. This is valid command as color shows.

![2020-10-19_22 53 20](https://user-images.githubusercontent.com/37061801/96460445-2a401280-125e-11eb-941e-5b7e8e789560.png)  
I gave myself that item via command block.

![2020-10-19_22 53 33](https://user-images.githubusercontent.com/37061801/96460551-49d73b00-125e-11eb-9854-483d598f00a5.png)  
Creating shop with valid syntax...

![2020-10-19_22 53 38](https://user-images.githubusercontent.com/37061801/96460621-5e1b3800-125e-11eb-86f0-d4be86da9031.png)  
Creating shop with item which is just created by command block.

![2020-10-19_22 53 43](https://user-images.githubusercontent.com/37061801/96460700-7428f880-125e-11eb-8a53-6738c0d30072.png)  
You can sell that item right after creating shop.

![2020-10-19_22 53 47](https://user-images.githubusercontent.com/37061801/96460731-80ad5100-125e-11eb-8632-a6af9724cbe6.png)
Let's do `/shop reload`

![2020-10-19_22 53 54](https://user-images.githubusercontent.com/37061801/96460761-8a36b900-125e-11eb-8dc6-4cb55b0e5db4.png)
Even though I gave myself same item before, I can't sell the item to shop.

### Version
 - Spigot version: [Paper 1.16.3]
 - Shop version: [1.8.2.2]

### Additional context
It seems `admin.yml` config file has every info I've used to make custom item. But shop doesn't accept that item after `/shop reload`.
